# Configuração do banco de dados
spring.datasource.url=jdbc:sqlserver://Medicare.mssql.somee.com;databaseName=Medicare;trustServerCertificate=true;
spring.datasource.username=Medicare_SQLLogin_1
spring.datasource.password=Medicare06@@
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# Logs para verificação da conexão com o banco de dados
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.com.microsoft.sqlserver.jdbc=DEBUG

# Configuração do JPA (caso você esteja usando Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.format_sql=true

# Logs do Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.hibernate.loader=DEBUG
vspring.jpa.hibernate.ddl-auto=create


# Log de erros (se você quiser logs mais detalhados em nível de erro)
logging.level.org.springframework.web=ERROR
